[21062022 02:50:06] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[21062022 02:50:06] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 02:50:06] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[21062022 02:50:06] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 02:50:53] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 02:50:53] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 02:50:53] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:50:53] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:50:53] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:50:53] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:50:53] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:50:53] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 02:50:53] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 02:50:58] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:50:58] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:50:59] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:50:59] MSSQL /dionaea/mssql/mssql.py:44-warning: Incomplete TDS_Header
[21062022 02:50:59] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:50:59] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:50:59] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:50:59] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:50:59] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:04] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:04] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:51:39] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:51:39] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:51:39] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:51:39] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:20] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:21] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 02:53:21] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:21] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:29] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:29] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:29] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:29] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/__init__.py:571 in None
[21062022 02:53:29] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:53:44] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 02:53:44] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 02:53:44] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 02:53:44] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 02:53:44] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03-\xc7\x07\xd5lN\xe1\xa9\xee\x999Qb\xdfyl\xd6\xd7\x96?\x8c\x142*\xcb5\x8f\xe2/\x80\xa2L''
[21062022 02:53:44] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03M\x1e\x81\xab\xe7\xfe\x10\xf0\x11>\xb4\x03%\x05#\xa5\xab\xa7p#n\xef\xc1\xb4+\x00y\xfag\x19S\xbe''
[21062022 02:53:44] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xe1\xea\xc2F\x9bQ\x80.\xb2\x8dJ\xf1)\x82\x9e6\x18J^\x0b\xfd\xe0\xe9]?\xf0l\xc2\x85]\xe4\x82''
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:699-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:44] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:699-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] ftp /dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:45] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:46] log_sqlite /dionaea/logsql.py:747-warning: no attackid for 172.17.0.2:443
[21062022 02:53:46] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:46] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:46] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:46] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:49] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:52] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 02:53:52] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:52] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:52] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:52] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:52] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:53:59] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:54:06] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:54:13] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:54:20] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:54:20] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 02:54:27] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 02:54:27] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 02:54:27] python /code/modules/python/module.c:1039-warning: OperationalError at database is locked
[21062022 02:54:27] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/sip/extras.py:99 in None
[21062022 02:54:27] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 02:54:27] python /code/modules/python/module.c:1065-warning: lib/d[21062022 04:26:42] python /code/modules/python/module.c:1039-warning: OSError at OSError(40, 'Too many levels of symbolic links')
[21062022 04:26:42] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/__init__.py:164 in None
[21062022 04:26:42] python /code/modules/python/module.c:1066-warning: 	 load_config_from_files
[21062022 04:26:42] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/ihandlers.py:30 in None
[21062022 04:26:42] python /code/modules/python/module.c:1066-warning: 	 new
[21062022 04:26:42] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[21062022 04:26:42] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:26:42] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:27:34] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f85266a88e0 w 0x562d5e07e5b0 revents 1024
[21062022 04:29:41] python /code/modules/python/module.c:1039-warning: OSError at OSError(40, 'Too many levels of symbolic links')
[21062022 04:29:41] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/__init__.py:164 in None
[21062022 04:29:41] python /code/modules/python/module.c:1066-warning: 	 load_config_from_files
[21062022 04:29:41] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/ihandlers.py:30 in None
[21062022 04:29:41] python /code/modules/python/module.c:1066-warning: 	 new
[21062022 04:29:41] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[21062022 04:29:41] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:29:41] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:30:18] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:18] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:18] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:30:18] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:30:24] sip /dionaea/sip/__init__.py:684-warning: Unknown SIP header: b'GET'
[21062022 04:30:24] MSSQL /dionaea/mssql/mssql.py:44-warning: Incomplete TDS_Header
[21062022 04:30:34] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:34] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:34] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:30:45] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:45] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:45] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:45] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:45] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:45] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:45] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:45] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:30:45] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:30:45] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:30:45] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:30:45] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:30:45] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:30:45] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:30:45] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:30:51] sip /dionaea/sip/__init__.py:684-warning: Unknown SIP header: b'GET'
[21062022 04:30:51] MSSQL /dionaea/mssql/mssql.py:44-warning: Incomplete TDS_Header
[21062022 04:30:57] sip /dionaea/sip/__init__.py:684-warning: Unknown SIP header: b'GET'
[21062022 04:30:57] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:31:06] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:11] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:16] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:26] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 04:31:31] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 04:31:39] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:42] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:31:49] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:54] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:31:59] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:32:09] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:32:19] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:32:27] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:32:42] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:32:57] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'SYST''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:33:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:33:17] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:33:17] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:33:17] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:699-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:17] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'PORT''
[21062022 04:33:18] ftp /dionaea/ftp.py:320-warning: Potential FTP Bounce Scan detected
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASV''
[21062022 04:33:18] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:18] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:33:18] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'SYST''
[21062022 04:33:18] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'STAT''
[21062022 04:33:18] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:33:18] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:18] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:24] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:24] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:33:25] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:25] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:25] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:25] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:32] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:39] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:33:46] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:33:54] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:01] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:08] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:08] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:34:08] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:08] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:34:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:34:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:35:08] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:35:08] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xda\x91\xb2\xa2\x87\x7f^\xd9\x05\xd0\x02\x82x9\xe4\xa03\x82\x1b\x85-c&\x19\xe6T)\xb1\xf14\xdd\x08''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b"\xd6\x04/\xce\xa6\x9a\xea\xda\xb9\xda7\x17\x9f\xbe\x03Z\xe2\xd7{\x00H\xf7\xcb\xaa<@3\x8d\x00\x9c\x13\x02\x13\x03\x13\x01\x003\x009\x005\x00/\xc0,\xc00\x00\xa3\x00\x9f\xcc\xa9\xcc\xa8\xcc\xaa\xc0\xaf\xc0\xad\xc0\xa3\xc0\x9f\xc0]\xc0a\xc0W\xc0S\xc0+\xc0/\x00\xa2\x00\x9e\xc0\xae\xc0\xac\xc0\xa2\xc0\x9e\xc0\\\xc0`\xc0V\xc0R\xc0$\xc0(\x00k\x00j\xc0s\xc0w\x00\xc4\x00\xc3\xc0#\xc0'\x00g\x00@\xc0r\xc0v\x00\xbe\x00\xbd\xc0"'
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\xc0\x14\x008\x00\x88\x00\x87\xc0\t\xc0\x13\x002\x00\x9a\x00\x99\x00E\x00D\x00\x9d\xc0\xa1\xc0\x9d\xc0Q\x00\x9c\xc0\xa0\xc0\x9c\xc0P\x00=\x00\xc0\x00<\x00\xba\x00\x84\x00\x96\x00A\x00\xff\x01\x00\x01\x17\x00\x0b\x00\x04\x03\x00\x01\x02\x00''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x00\x0c\x00''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x00\x1d\x00\x17\x00\x1e\x00\x19\x00\x18\x00#\x00\x00\x00\x16\x00\x00\x00\x17\x00\x00\x00''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x000\x00.\x04\x03\x05\x03\x06\x03\x08\x07\x08\x08\x08\t\x08''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x00W\x01\x00\x00S\x03\x03b\xb1J}\x94?\xe4\x12\xf8\xcby\xe3\x8e\xba\xd6\x026\xa9\xcd\x18=\xaeB''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'A*\x00\x1cr\xa4\x82\x0c\x00\x00''
[21062022 04:35:08] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x00/\x00''
[21062022 04:35:08] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:35:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:36:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:37:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:38:40] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:39:07] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f01f71038e0 w 0x5567c3d7fbb0 revents 1024
[21062022 04:39:21] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[21062022 04:39:21] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:39:21] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:39:21] binding /dionaea/hpfeeds.py:138-warning: All arguments of __init__ must have a default value. class: 'hpclient', arg: 'server'
[21062022 04:39:21] python /code/modules/python/module.c:1039-warning: LoaderError at LoaderError()
[21062022 04:39:21] python /code/modules/python/module.c:1065-warning: binding.pyx:457 in None
[21062022 04:39:21] python /code/modules/python/module.c:1066-warning: 	 dionaea.core.connection.__init__
[21062022 04:39:21] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:138 in None
[21062022 04:39:21] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 04:39:21] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:283 in None
[21062022 04:39:21] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 04:39:21] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:60 in None
[21062022 04:39:21] python /code/modules/python/module.c:1066-warning: 	 start
[21062022 04:39:21] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/ihandlers.py:45 in None
[21062022 04:39:21] python /code/modules/python/module.c:1066-warning: 	 start
[21062022 04:39:33] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:33] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:36] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:36] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:36] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:40] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 04:39:40] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 04:39:41] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:39:41] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:39:47] sip /dionaea/sip/__init__.py:684-warning: Unknown SIP header: b'GET'
[21062022 04:39:47] MSSQL /dionaea/mssql/mssql.py:44-warning: Incomplete TDS_Header
[21062022 04:39:53] sip /dionaea/sip/__init__.py:684-warning: Unknown SIP header: b'GET'
[21062022 04:39:53] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:40:02] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:07] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:12] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:40:22] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 04:40:27] pptp /dionaea/pptp/pptp.py:67-warning: Bad PPTP Packet, Length = 0
[21062022 04:40:34] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:44] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:49] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:40:54] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:41:04] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:41:14] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:41:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:41:22] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:41:52] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:42:12] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:42:12] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:699-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:42:12] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:12] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:42:12] ftp /dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[21062022 04:42:12] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:42:13] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:42:13] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:42:13] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'SYST''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'PORT''
[21062022 04:42:13] ftp /dionaea/ftp.py:320-warning: Potential FTP Bounce Scan detected
[21062022 04:42:13] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASV''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'SYST''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'STAT''
[21062022 04:42:13] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:42:19] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:19] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:19] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:19] SMB /dionaea/smb/smb.py:836-warning: epmapper - not enough data
[21062022 04:42:19] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:20] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:42:26] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:33] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:41] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:48] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:42:55] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:43:02] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:43:09] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:16] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:16] http /dionaea/http.py:133-warning: max_num_fields is only supported with Python >= 3.8
[21062022 04:43:16] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:16] ftp /dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[21062022 04:43:16] mysqld /dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[21062022 04:43:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'QUIT''
[21062022 04:43:17] connection /code/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[21062022 04:43:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb7(>\\\x12\xe6g\x1d\xb4"\xd8J\xd2\x97\xe6\xdc||\xccd\xb3\xaa\x8au\xbeZ\x96\x00\xe6\xea!/''
[21062022 04:43:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x16\x03\x01\x00W\x01\x00\x00S\x03\x03b\xb1Le\xae\x0e\xb5\xa3\xaf\xfa\xff\xae\x8c\xbe\x9c8A>\x8e\xcc\x93.\xb7A9\xf1#\xcd=''
[21062022 04:43:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'*u\x00\x00''
[21062022 04:43:17] ftp /dionaea/ftp.py:235-warning: cmd 'b'\x00/\x00''
[21062022 04:43:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:44:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:45:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:46:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:47:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:48:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:49:20] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:50:09] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f70152e78e0 w 0x555688f81410 revents 1024
[21062022 04:50:25] sip /dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[21062022 04:50:25] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:50:25] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[21062022 04:50:25] binding /dionaea/hpfeeds.py:138-warning: All arguments of __init__ must have a default value. class: 'hpclient', arg: 'server'
[21062022 04:50:25] python /code/modules/python/module.c:1039-warning: LoaderError at LoaderError()
[21062022 04:50:25] python /code/modules/python/module.c:1065-warning: binding.pyx:457 in None
[21062022 04:50:25] python /code/modules/python/module.c:1066-warning: 	 dionaea.core.connection.__init__
[21062022 04:50:25] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:138 in None
[21062022 04:50:25] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 04:50:25] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:283 in None
[21062022 04:50:25] python /code/modules/python/module.c:1066-warning: 	 __init__
[21062022 04:50:25] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/hpfeeds.py:60 in None
[21062022 04:50:25] python /code/modules/python/module.c:1066-warning: 	 start
[21062022 04:50:25] python /code/modules/python/module.c:1065-warning: lib/dionaea/python/dionaea/ihandlers.py:45 in None
[21062022 04:50:25] python /code/modules/python/module.c:1066-warning: 	 start
[21062022 04:51:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:52:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:53:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:54:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:55:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:56:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:57:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:58:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 04:59:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:00:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:01:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:02:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:03:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:04:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:05:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:06:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:07:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:08:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:09:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:10:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:11:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:12:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:13:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:14:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:15:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:16:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:17:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:18:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:19:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:20:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:21:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:22:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:23:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:24:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:25:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:26:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:27:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:28:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:29:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:30:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:31:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:32:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:33:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:34:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:35:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:36:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:37:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:38:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:39:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:40:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:41:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:42:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:43:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:44:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:45:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:46:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:47:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:48:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:49:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:50:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:51:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:52:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:53:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:54:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:55:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:56:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:57:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:58:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 05:59:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:00:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:01:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:02:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:03:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:04:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:05:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:06:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:07:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:08:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:09:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:10:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:11:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:12:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:13:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:14:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:15:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:16:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:17:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:18:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:19:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:20:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:21:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:22:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:23:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:24:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:25:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:26:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:27:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:28:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:29:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:30:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:31:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:32:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:33:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:34:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:35:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:36:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:37:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:38:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:39:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:40:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:41:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:42:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:43:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:44:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:45:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:46:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:47:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:48:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:49:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:50:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:51:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:52:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:53:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:54:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:55:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:56:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:57:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:58:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 06:59:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:00:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:01:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:02:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:03:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:04:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:05:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:06:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:07:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:08:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:09:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:10:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:11:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:12:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:13:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:14:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:15:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:16:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:17:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:18:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:19:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:20:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:21:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:22:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:23:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:24:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:25:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:26:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:27:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:28:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:29:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:30:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:31:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:32:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:33:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:34:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:35:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:36:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:37:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:38:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:39:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:40:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:41:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:42:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:43:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:44:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:45:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:46:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:47:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:47:42] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 07:48:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:49:02] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 07:49:02] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 07:49:02] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 07:49:21] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 07:49:21] connection /code/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[21062022 07:49:21] connection /code/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[21062022 07:49:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:50:26] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:50:28] ftp /dionaea/ftp.py:235-warning: cmd 'b'USER''
[21062022 07:50:31] ftp /dionaea/ftp.py:235-warning: cmd 'b'PASS''
[21062022 07:50:31] ftp /dionaea/ftp.py:235-warning: cmd 'b'SYST''
[21062022 07:50:34] ftp /dionaea/ftp.py:235-warning: cmd 'b'PORT''
[21062022 07:50:34] binding /dionaea/ftp.py:580-warning: All arguments of __init__ must have a default value. class: 'FTPDataConnect', arg: 'host'
[21062022 07:51:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:52:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:53:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:54:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:55:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:56:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:57:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:58:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 07:59:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 08:00:25] sip /dionaea/sip/__init__.py:45-warning: Cleanup
[21062022 08:00:54] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7f9b6594a8e0 w 0x56198da2ad20 revents 1024
